### ISSUE TITLE
最新バージョン(1.8.2)をnpm publishする

### ISSUE THREAD

**Issue by exKAZUu** [shiguredo/sora-js-sdk#10]
https://www.npmjs.com/package/sora-js-sdk に記載されている通り、バージョン1.8.0までしか公開されていないようです。差し支えなければ、1.8.2を公開していただけないでしょうか。ご検討いただければ幸いです。

**Comment by voluntas** [comment]
@exKAZUu お問い合わせありがとうございます。そちらのパッケージ実は弊社で公開したものではないため、ちょっとどうしたらいいか検討中です。お待ちいただければと思います。

**Comment by voluntas** [comment]
@exKAZUu とりあえずの対応ですが package.json に git を指定して一時的に回避していただければと思います。

https://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version

**Comment by exKAZUu** [comment]
@voluntas ご回答ありがとうございます。ご指摘の通りgitで指定しておりますので大きな支障は出ておりません。お時間があるときにでもご確認いただければ幸いです。

**Comment by voluntas** [comment]
@exKAZUu ありがとうございます。現在そちらのリポジトリを公開している関係者に問い合わせのメールを送り待っている状態です。お待ちいただければと思います。

**Comment by voluntas** [comment]
こちら一度削除してもらいました。公開については一度社内にて検討してから進めさせていただきます。いろいろとありがとうございました！
