### ISSUE TITLE
マルチストリームで複数クライアントが同時に接続および通話を開始すると失敗する

### ISSUE THREAD

**Issue by exKAZUu** [shiguredo/sora-js-sdk#13]
### 環境
- OS: Mac OS High Sierra (10.13.5) および Windows 10
- ブラウザ: Electron 2.0.2, 1.8.7, 1.7.15
- sora: sora-18.04.3
- sora-js-sdk: master, 1.9.0, 1.8.2

### 症状
複数のElectronアプリを立ち上げ、マルチストリームを有効にした状態で、同時にSoraへ接続して通話を開始すると、 `ICECANDIDATE TIMEOUT` 等のエラーが発生して、通話を開始できません。
1台のPCでも、同じローカルネットワーク内の2台のPCでも、同時に接続するとエラーが発生します。

### 再現手順
https://github.com/UsideU/sora-js-sdk-issuue にリプロダクション用の最小セットを用意しました。

別途、ログ等はメールにてお送りいたします。

**Comment by voluntas** [comment]
@exKAZUu こちら、弊社内でも確認できました。修正版を今週中に提供予定です。

もう少々お待ち下さい。詳細なご報告本当にありがとうございます。

**Comment by voluntas** [comment]
@exKAZUu 最新版での動作確認ありがとうございました。もしなにか不具合ありましたら、別途 issues をオープンしていただければと思います。
