### ISSUE TITLE
Add TypeScript type definition

### ISSUE THREAD

**Issue by exKAZUu** [shiguredo/sora-js-sdk#16]
既にFlowの型情報があるので、それを参考にTypeScriptの型定義ファイルを追加したいです。
よろしければ、追加のためのPRを作成いたしますが、本リポジトリにPRを投げるべきか、 https://github.com/DefinitelyTyped/DefinitelyTyped にPRを投げるべきか悩んだため、確認も兼ねて本チケットを作成しました。

（なお、個人的には、そこまで型情報が複雑ではないので、本リポジトリでメンテしても良いのではないかと思いました。
とはいえ、今後、貴社でメンテ作業が発生することになってしまいますね・・。）

**Comment by voluntas** [comment]
@exKAZUu 現時点では TypeScript の型情報を更新していく予定がないため、 PR 頂いてもマージすることが難しいのが現状です。そのため https://github.com/DefinitelyTyped/DefinitelyTyped に PR を投げていただくかするのが良いかと思います。

大変ありがたいお申し出なのですが、自社でメンテナンス保証をできないものを提供してくのは難しいためご理解いただければと思います。

ただ、TypeScript の型情報の提供は今後どうしていくか社内で検討してみます。

**Comment by exKAZUu** [comment]
@voluntas ご回答有り難うございます。承知しました、そのようにいたします。

ところで、Flowの型情報を拝見していて、 https://github.com/shiguredo/sora-js-sdk/blob/develop/src/sora.js#L2-L9 からは `audio` と `video` が必須項目であるように読めます。
しかし、これまでオプションには `{ multistream: true }` だけを渡しており、動作はしておりました。
TSの型情報を作る際に参考したく、`audio` と `video` は必須項目とすべきかどうかご教示いただけないでしょうか。

**Comment by exKAZUu** [comment]
@voluntas ありがとうございます、承知しました。
(となると、flowの型定義でも audio / video に `?` を付けた方が良いように思います。)

**Comment by voluntas** [comment]
@exKAZUu たしかにそうですね。オプションにしておきます。ありがとうございます！
