### ISSUE TITLE
シグナリングの接続タイムアウトを検知できるようにしたいです

### ISSUE THREAD

**Issue by bemarble** [shiguredo/sora-js-sdk#31]
SoraへWebsocketでシグナリングの要求を行い、一定時間応答が無い場合タイムアウトとする実装を行いたいです。
現在、SoraへのWebsocketの接続タイムアウトまで約3分程度待つ状態が発生します。

下記のように実装するとタイムアウトを検知できることが確認できました。
https://github.com/bemarble/sora-js-sdk/commit/1fc0c2b9d1662edeb2c5d25af9677b9ac60b990b

もし別の方法ですでに検知可能であればご教示いただけますと幸いです。

**Comment by voluntas** [comment]
@bemarble 3 分程度待つ状態というのは Sora の仕様的には存在しないのですが、sys.config の設定でなにか設定されたりしていますでしょうか？

Sora に関係するタイムアウトの情報は以下の通りです

- WebSocket が確立したあとにメッセージが送られてこなければ 5 秒で切断します
- type: connect が送られてきて offer/answer 後に、 WebRTC が確立しなければデフォルトでは 30 秒で切断します
   - これは connection_created_wait_timeout の値に依存します
   - https://sora.shiguredo.jp/doc/SYS_CONFIG.html#connection-created-wait-timeout
- TCP すら確立されていない場合は OS の設定に依存します

約 3 分 はサーバ側の設定都合な気がしています。今の時点では SDK 側でタイムアウトを処理する必要があるのかわからないため、詳細についてお教えいただければと思います。

Sora の方針としては早めに切断するに寄せています。

**Comment by bemarble** [comment]
@voluntas 
ご回答ありがとうございます。

Soraへの名前解決ができない場合など、サーバまで到達できない場合の事象となります。
サーバへの経路が確立していて接続ができない場合は、Soraで設定した値でのタイムアウトは確認できております。
3分という設定は定かな値ではございませんが、Google chrome にて長時間接続が確立できない場合、
下記のエラーが発生しておりました。
`WebSocket is closed before the connection is established.`

（提示させていただいたコードでSDKの外からもタイムアウトを設定して検知することは可能でした。）

**Comment by voluntas** [comment]
@bemarble なるほど、TCP 接続前の話でしたか。それであれば確かにタイムアウトはあったほうが良さそうに感じています。ただおっしゃるとおりで SDK の外からもタイムアウトの仕組み自体は作れるということもあり、SDK に組み込むかは悩ましいです。少しお時間いただければと思います。

もし組み込む場合は websocket だけの timeout ではなく、 SDK として ICE 関連も含んだ SDK としての timeout を提供する形になりそうです。

**Comment by bemarble** [comment]
@voluntas 
たしかに考慮する箇所は他にもありそうですね。
ご検討いただきありがとうございます。

**Comment by voluntas** [comment]
@bemarble SDK として Sora に接続できずにタイムアウトできるようにするという仕組みをいれる方向で進めています。お時間いただくと思いますがお待ちいただければと思います。

**Comment by voluntas** [comment]
@bemarble おまたせしました、develop に timeout 機能を追加しましたので、確認いただければと思います。

**Comment by bemarble** [comment]
@voluntas 
ご対応ありがとうございます。
確認いたします。

**Comment by bemarble** [comment]
@voluntas 
soraサーバへの接続ができない状況を用意してSDKにオプションを設定し、意図した時間でタイムアウトがSDKから返却されることを確認できました。
ありがとうございます。

*エラーメッセージ*
`Error: "CONNECTION TIMEOUT"`

**Comment by voluntas** [comment]
@bemarble 確認ありがとうございます。develop の整理が済み次第、リリースをさせていただきます。

**Comment by voluntas** [comment]
@bemarble  今回の修正を含んだ 1.16.0 をリリースしました。https://github.com/shiguredo/sora-js-sdk/releases/tag/1.16.0
