### ISSUE TITLE
ConnectionPublisher の metadata にoptional parameter をもつオブジェクトを渡したい

### ISSUE THREAD

**Issue by tatane616** [shiguredo/sora-js-sdk#38]
`ConnectionPublisher` に渡す `metadata` ですが、現在の型定義ですと optional parameter を利用できません

```ts
sendrecv(channelId: string, metadata?: Json, options?: ConnectionOptions): ConnectionPublisher;

...

export declare type Json = null | boolean | number | string | Json[] | {
    [prop: string]: Json;
};
```

以下のような optional parameter を持つオブジェクトを metadata として渡すように型を拡張することは考えておられますでしょうか？
```ts
type Metadata = {
  foo: string
  bar?: boolean
}
```

拡張する場合、本リポジトリにPRを投げてもよろしいでしょうか

**Comment by voluntas** [comment]
@tatane616 README に書いてあるとおり、まずは Discord へお願いします。一旦こちらの Issues は閉じさせていただきます。

**Comment by tatane616** [comment]
@voluntas 承知いたしました、README の確認不足申し訳ありません 🙇
