### ISSUE TITLE
error development in react typescript environment : Declaration or statement expected.  TS1128

### ISSUE THREAD

**Issue by danilrafiqi** [shiguredo/sora-js-sdk#43]
this is the error i got when develop using react typescript
Declaration or statement expected.  TS1128
this error from 'type' in file sora.d.ts in the last of line code.

Failed to compile.

C:/danilrafiqi/node_modules/sora-js-sdk/dist/sora.d.ts
TypeScript error in C:/danilrafiqi/node_modules/sora-js-sdk/dist/sora.d.ts(20,1):    
Declaration or statement expected.  TS1128

    18 | };
    19 | export default _default;
  > 20 | export type { AudioCodecType, Callbacks, ConnectionBase, ConnectionOptions, ConnectionPublisher, ConnectionSubscriber, Role, SimulcastQuality, SoraConnection, VideoCodecType }; 
       | ^
    21 |
    22 |
![Capture](https://user-images.githubusercontent.com/22560475/95161445-65a60000-07cd-11eb-8c4f-2aeb35c5ce49.PNG)

**Comment by voluntas** [comment]
Discord で相談のない Issue は閉じます。またドキュメントに書いてあるとおり日本語以外の Issue は対応しません。
