### ISSUE TITLE
Subscriber の multistream 対応を希望します

### ISSUE THREAD

**Issue by mganeko** [shiguredo/sora-js-sdk#5]
複数のPublisherがmultistreamで接続しているchannelに、Subscriberとして接続して複数のdownstreamを受け取れるようにできないでしょうか？

```
options.multistream = true; 
```

を指定した場合に、次のイベントを受け取れることを想定しています。

- on('addstream')
- on('removestream')

**Comment by yuitowest** [comment]
@mganeko バージョン 1.2.0 で対応しました。

**Comment by mganeko** [comment]
対応ありがとうございます。
動作確認しました。バッチリ動きました。
