### ISSUE TITLE
soraからの’notify’イベントの通知に関して

### ISSUE THREAD

**Issue by iPre-Innovate** [shiguredo/sora-js-sdk#6]
Soraのsys.configにて以下の設定を行い
https://sora.shiguredo.jp/doc/SIGNALING.html#type-notify

通知を有効化（有効化の確認方法がLog等でわかりますでしょうか）したと思いますが
本sora-js-sdkにて’notify’イベントを受け取ることは可能でしょうか？

APIの記載にあるように、以下のコードも受け取れなかったです
```
publish.on('notify',(e)=>{});
subscribe.on(notify',(e)=>{});
```
またソースの`base.js`も拝見しましたが`this._ws.onmessage`には該当する`notify`イベントには対応していないように見受けられます。

本SDKでの対応可否でも結構ですので教えていただければと思います

**Comment by yuitowest** [comment]
@iPre-Innovate 未対応だったため、バージョン 1.4.0 にて対応しました。
```
publish.on('notify',(e)=>{});
```
で、type: notify 時のイベントを受け取ることができます。
バージョンを上げて確認して頂ければと思います。

**Comment by iPre-Innovate** [comment]
迅速な対応ありがとうございます
`notify`イベント確認できました
