### ISSUE TITLE
metadata が access_token になってしまっています

### ISSUE THREAD

**Issue by voluntas** [shiguredo/sora-js-sdk#7]
17.04 で metadata のみになったので修正をお願いします。

https://github.com/shiguredo/sora-js-sdk/blob/48aa3f59fdad672bba689eabb265fd5fb1f375d5/src/utils.js#L39

**Comment by yuitowest** [comment]
[1.4.1](https://github.com/shiguredo/sora-js-sdk/releases/tag/1.4.1) にて対応しました

**Comment by voluntas** [comment]
確認しました、対応ありがとうございます
